apiVersion: v1
kind: Service
metadata:
  name: prod-registry
spec:
  clusterIP: 10.43.0.51
  # Unlike builds-registry we don't have type: NodePort because prod-registry
  # is intended for image pull of pre-built images at container start
  # and as base images in in-cluster builds
