apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  labels: &labels
    app: git-source
    type: gitea
spec:
  replicas: 1
  serviceName: "gitea"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.13.4@sha256:11b53cd7bd6bd926342ee7fbbde97b5d112d26de9606809f7cefb8a1191e0d3a
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: git-data
          mountPath: /data
        - name: logs
          mountPath: /var/log/gitea
      volumes:
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: git-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
