apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  labels: &labels
    app: git-source
    type: gitea
spec:
  replicas: 1
  serviceName: "gitea"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.11.2@sha256:b524d98f1eea0b731265115478a0c3b54b72685b089cf8fb019eb59d6f51f3f6
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: git-data
          mountPath: /data
        - name: logs
          mountPath: /var/log/gitea
      volumes:
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: git-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
