apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: builds.registry.svc.cluster.local/ystack-examples/api-nodejs
    context: ./api-nodejs
    custom:
      buildCommand: ../../ystack-build.sh
      # To use a non-default dockerfile or layer:
      #buildCommand: ../../ystack-build.sh --opt filename=dev.Dockerfile --opt target=target1
      dependencies:
        dockerfile:
          path: ./Dockerfile
    # TODO nodemon and verify sync path
    #sync:
    #  manual:
    #  - src: src/**
    #    dest: /usr/src/app
deploy:
  kustomize:
    path: ./variant-dev
