apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-etc-hosts-update
spec:
  selector:
    matchLabels:
      app: registry-etc-hosts-update
  template:
    metadata:
      labels:
        app: registry-etc-hosts-update
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      initContainers:
      - name: update
        image: debian:stretch-slim@sha256:9490c476443a3869e39c2897fa66c91daf5dcbbfca53c976dac7bbdc45775b28
        volumeMounts:
        - name: etchosts
          mountPath: /host-etc/hosts
          readOnly: false
        env:
        - name: REGISTRY_SERVICE_HOSTS
          value: >-
            builds-registry.ystack.svc.cluster.local
            prod-registry.ystack.svc.cluster.local
        command:
        - bash
        - -ce
        - |
          NL=$'\n'
          HOSTS="$(cat /host-etc/hosts)"
          for H in $REGISTRY_SERVICE_HOSTS; do
            ent=""
            [ ! -z "$FIXED_IP" ] && ent="$FIXED_IP   $H";
            [ -z "$ent" ] && ent=$(getent hosts $H);
            [ -z "$ent" ] && echo "Failed to get hosts entry for $H" && exit 1;
            echo "$HOSTS" | grep " $H"  || HOSTS="$HOSTS$NL$ent";
            echo "$HOSTS" | grep "$ent" || HOSTS=$(echo "$HOSTS" | sed "s|.* $H|$ent|");
          done;
          echo "$HOSTS" | diff -u /host-etc/hosts - || echo "$HOSTS" > /host-etc/hosts
          echo "Done."
      containers:
      - name: init-container-did-the-work
        image: gcr.io/google_containers/pause-amd64:3.1@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etchosts
        hostPath:
          path: /etc/hosts
