# Deprecated (maybe), kept while the minio instance was renamed
apiVersion: v1
kind: Service
metadata:
  name: blobs-minio
  labels:
    app: minio
    release: blobs
spec:
  selector:
    v1beta1.min.io/instance: minio
  ports:
  - name: http
    port: 80
    targetPort: 9000
