apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  labels:
    app: git-source
    type: gitea
spec:
  replicas: 1
  serviceName: "gitea"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: git-source
      type: gitea
  template:
    metadata:
      labels:
        app: git-source
        type: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.15.6@sha256:58b3e0abc250b1b4205dbf5705dbb50fac5914eb5b552615f899764e487995f5
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: git-data
          mountPath: /data
        - name: logs
          mountPath: /var/log/gitea
      volumes:
      - name: logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: git-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
