apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ystack # install's app_url depends on namespace

resources:
- git-service.yaml
- gitea-statefulset-service.yaml
- gitea-statefulset.yaml

images:
- name: gitea/gitea
  newName: docker.io/gitea/gitea
  newTag: 1.16.8@sha256:b0bdf102b485fd8befd564e2473f045f260eaf1b29c9fdcb9b415d1564cba332
