apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ystack # install's app_url depends on namespace

resources:
- git-service.yaml
- gitea-statefulset-service.yaml
- gitea-statefulset.yaml

images:
- name: gitea/gitea
  newName: docker.io/gitea/gitea
  newTag: 1.16.5@sha256:862ac2762dd67f8953678a4c3476ec373ac9f581d7dea8b78a30c51a305e5e80
