apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dockerd
spec:
  selector:
    matchLabels:
      app: dockerd
  serviceName: "dockerd"
  replicas: 1
  template:
    metadata:
      labels:
        app: dockerd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: dockerd
        image: docker:19.03.2-dind@sha256:615eb3922630a30a52f7c46760f3d08a9eb4a1b0474d038281af8eade8c43f40
        securityContext:
          privileged: true
        args:
        - dockerd
        ports:
        - containerPort: 2376
          name: docker-tcp
        volumeMounts:
        - name: etc-docker
          mountPath: /etc/docker/daemon.json
          subPath: daemon.json
      volumes:
      - name: etc-docker
        configMap:
          name: etc-docker
