apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dockerd
spec:
  selector:
    matchLabels:
      app: dockerd
  serviceName: "dockerd"
  replicas: 1 # Can't be scaled up because legacy build caching requires a volume. Use buildkitd instead.
  template:
    metadata:
      labels:
        app: dockerd
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: setup
        image: busybox@sha256:49dae530fd5fee674a6b0d3da89a380fc93746095e7eca0f1b70188a95fd5d71
        volumeMounts:
        - name: build-cache
          mountPath: /var/lib/docker/overlay2
        - name: var-lib-docker
          mountPath: /var/lib/docker
        command:
        - /bin/sh
        - -cex
        - |
          # https://github.com/docker/docker-ce/blob/ce5b02683e83ec9aa89927a9ce5d276787cc8823/components/engine/daemon/graphdriver/overlay2/overlay.go#L148
          # but we want a single volume mount that preserves build cache only
          [ -d /var/lib/docker/overlay2/var-lib-docker-image ] || mkdir /var/lib/docker/overlay2/var-lib-docker-image
          ln -s /var/lib/docker/overlay2/var-lib-docker-image /var/lib/docker/image
      containers:
      - name: dockerd
        image: docker:20.10.1-dind@sha256:b890370b484eb4d72989e632b524bdfb482f939bb5af4a6739445e26ba564368
        securityContext:
          privileged: true
        args:
        - dockerd
        ports:
        - containerPort: 2376
          name: docker-tcp
        volumeMounts:
        - name: etc-docker
          mountPath: /etc/docker/daemon.json
          subPath: daemon.json
        - name: build-cache
          mountPath: /var/lib/docker/overlay2
        - name: var-lib-docker
          mountPath: /var/lib/docker
      volumes:
      - name: etc-docker
        configMap:
          name: etc-docker
      - name: var-lib-docker
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: build-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
