apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dockerd
spec:
  selector:
    matchLabels:
      app: dockerd
  serviceName: "dockerd"
  replicas: 1 # Can't be scaled up because legacy build caching requires a volume. Use buildkitd instead.
  template:
    metadata:
      labels:
        app: dockerd
      annotations:
        container.apparmor.security.beta.kubernetes.io/dockerd: unconfined
        container.seccomp.security.alpha.kubernetes.io/dockerd: unconfined
    spec:
      terminationGracePeriodSeconds: 25
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: setup
        image: docker:dind-rootless
        volumeMounts:
        - name: etc-docker-config
          mountPath: /home/rootless/docker-config
        - name: etc-docker
          mountPath: /home/rootless/.config/docker
        - name: build-cache
          mountPath: /var/lib/docker/overlay2
        - name: var-lib-docker
          mountPath: /var/lib/docker
        command:
        - /bin/sh
        - -cex
        - |
          # https://github.com/docker/docker-ce/blob/ce5b02683e83ec9aa89927a9ce5d276787cc8823/components/engine/daemon/graphdriver/overlay2/overlay.go#L148
          # but we want a single volume mount that preserves build cache only
          [ -d /var/lib/docker/overlay2/var-lib-docker-image ] || mkdir /var/lib/docker/overlay2/var-lib-docker-image
          ln -s /var/lib/docker/overlay2/var-lib-docker-image /var/lib/docker/image
          cp /home/rootless/docker-config/* /home/rootless/.config/docker/
      containers:
      - name: dockerd
        image: docker:dind-rootless
        securityContext:
          privileged: true
        env:
        - name: DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS
          value: "-p 0.0.0.0:2376:2376/tcp"
        args:
        - dockerd
        ports:
        - containerPort: 2376
          name: docker-tcp
        volumeMounts:
        - name: etc-docker
          mountPath: /home/rootless/.config/docker
        - name: build-cache
          mountPath: /var/lib/docker/overlay2
        - name: var-lib-docker
          mountPath: /var/lib/docker
      volumes:
      - name: etc-docker-config
        configMap:
          name: etc-docker
      - name: etc-docker
        emptyDir: {}
      - name: var-lib-docker
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: build-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
