apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: docker:dind
  newName: docker
  newTag: 20.10.12-dind

resources:
- dockerd-service.yaml
- dockerd-statefulset.yaml

configMapGenerator:
- name: etc-docker
  files:
  - daemon.json
