apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: docker:dind
  newName: docker
  newTag: 20.10.11-dind@sha256:1ff5e500e2d42048923c1243ad26691c83c65406a33086f56e02e4fb2d43ecd8

resources:
- dockerd-service.yaml
- dockerd-statefulset.yaml

configMapGenerator:
- name: etc-docker
  files:
  - daemon.json
