apiVersion: v1
kind: Service
metadata:
  name: buildkitd-nodeport
  labels:
    ystack-kubefwd: never
spec:
  type: NodePort
  ports:
  - port: 8547
    protocol: TCP
  selector:
    app: buildkitd
    status: accepts-new-builds
