# include this resource in any kustomization.yaml, and add to all ingresses:
#  tls:
#  - secretName: tls-local
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: tls-local
  # See ../tls-local.sh for an example of how to generate a cert
  files:
  - tls.crt
  - tls.key
