# include this resource in any kustomization.yaml, and add to all ingresses:
#  tls:
#  - secretName: tls-local
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: tls-local
  files:
  - tls.crt
  - tls.key
