apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- release.yaml

# To override config add config maps like:
# configMapGenerator:
# - name: config-artifact-bucket
#   literals:
#   - location=gs://my-actual-bucket
#   options:
#     disableNameSuffixHash: true
#     labels:
#       app.kubernetes.io/instance: default
#       app.kubernetes.io/part-of: tekton-pipelines
#   namespace: tekton-pipelines
#   behavior: replace
