apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- release.yaml

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: tekton-pipelines-controller
  # Note: the args list may change at Tekton upgrade; verify that the debug-nonroot image comes after the -shell-image arg
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/17
      value: gcr.io/distroless/base:debug-nonroot@sha256:8f330306c95420a801c399e449518b7be79db7e8916075a6a4cb1be91550200d

# To override config add config maps like:
# configMapGenerator:
# - name: config-artifact-bucket
#   literals:
#   - location=gs://my-actual-bucket
#   options:
#     disableNameSuffixHash: true
#     labels:
#       app.kubernetes.io/instance: default
#       app.kubernetes.io/part-of: tekton-pipelines
#   namespace: tekton-pipelines
#   behavior: replace
