kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zonal-pd-resizable-retain
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-standard
