kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zonal-ssd-resizable-delete
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  type: pd-ssd
