apiVersion: batch/v1
kind: Job
metadata:
  name: ystack-installer-knative
  labels: &labels
    kontrakt: completion
  annotations:
    image-registry: &registry builds.registry.svc.cluster.local/knative-serving
spec:
  backoffLimit: 0
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: ystack-installer-knative
      initContainers:
      - name: istio
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        command:
        - sh
        - -cex
        - |
          kubectl apply -k github.com/Yolean/unhelm/istio/crds?ref=390bdbc6bfd03bd09edbf271afe466f09e8d4a6e
          sleep 5
          kubectl apply -k github.com/Yolean/unhelm/istio/namespace?ref=390bdbc6bfd03bd09edbf271afe466f09e8d4a6e
          kubectl apply -f https://github.com/Yolean/unhelm/raw/390bdbc6bfd03bd09edbf271afe466f09e8d4a6e/istio/knative-istio-lean.yaml
      - name: serving-crd-fix
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        command:
        - sh
        - -cex
        - |
          kubectl apply -f https://github.com/knative/serving/raw/cb5c1810f2690efa0c434bc81aab3a1d45df497f/vendor/github.com/knative/caching/config/image.yaml
      - name: serving
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        env:
        - name: KO_DOCKER_REPO
          value: *registry
        - name: KO_SOURCE
          value: github.com/knative/serving
        - name: KO_REVISION
          value: cb5c1810f2690efa0c434bc81aab3a1d45df497f
      - name: serving-config
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        command:
        - sh
        - -cex
        - |
          cat << EOF | kubectl apply -f -
          # avoid subdomains as they are impractical wrt SSL cert management
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config-network
            namespace: knative-serving
          data:
            domainTemplate: "{{.Name}}--{{.Namespace}}.{{.Domain}}"
          EOF
      - name: eventing
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        env:
        - name: KO_DOCKER_REPO
          value: *registry
        - name: KO_SOURCE
          value: github.com/knative/eventing
        - name: KO_REVISION
          value: ab2600952f58339a0c8f673a712c4acdd5912757
      - name: eventing-channel-inmemory
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        env:
        - name: KO_DOCKER_REPO
          value: *registry
        - name: KO_SOURCE
          value: github.com/knative/eventing
        - name: KO_REVISION
          value: ab2600952f58339a0c8f673a712c4acdd5912757
        - name: KO_APPLY_PATH
          value: config/provisioners/in-memory-channel/in-memory-channel.yaml
      - name: eventing-channel-kafka
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        env:
        - name: KO_DOCKER_REPO
          value: *registry
        - name: KO_SOURCE
          value: github.com/knative/eventing
        - name: KO_REVISION
          value: ab2600952f58339a0c8f673a712c4acdd5912757
        - name: KO_APPLY_PATH
          value: contrib/kafka/config
      - name: eventing-config-kafka
        image: solsson/go-ko-runner@sha256:cd41533cc951f7baba33dca2282d248045196f9afd41e2780d5c64f151194788
        command:
        - sh
        - -cex
        - |
          cat << EOF | kubectl apply -f -
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config-kafka
            namespace: knative-eventing
          data:
            bootstrapServers: bootstrap.kafka:9092
          EOF
      containers:
      - name: done
        image: busybox
        command: ["echo", "Installation done. See init container logs for details."]
      restartPolicy: Never
