apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
spec:
  template:
    spec:
      containers:
      - name: metrics-server
        args:
        - --metric-resolution=10s