[registry."builds-registry.ystack.svc.cluster.local"]
  mirrors = ["builds-registry.ystack.svc.cluster.local:80"]
  http = true
[registry."prod-registry.ystack.svc.cluster.local"]
  mirrors = ["prod-registry.ystack.svc.cluster.local:80"]
  http = true
