apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: moby/buildkit:rootless
  newName: docker.io/moby/buildkit
  newTag: v0.10.1-rootless@sha256:6be280737e068d09ed9bc4b43b8690c80ce54e97dd70f4535111d52d5004b13a

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
