apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: moby/buildkit:rootless
  newName: docker.io/moby/buildkit
  newTag: v0.10.0-rootless@sha256:5c299fd63d5aae2595821bd6e0053c96f990fb9f5b0ab3e17ecba071e87286d8

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
