apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: moby/buildkit:rootless
  newName: docker.io/moby/buildkit
  newTag: v0.9.3-rootless@sha256:d877f877f7411804fefaf90071464913130f8d34fe5797ac2f7164ddf816d27c

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
