apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: moby/buildkit:rootless
  newName: docker.io/moby/buildkit
  newTag: v0.10.3-rootless@sha256:22e39442689ddbfd938892b33a12cc9bc76c7e71e07cbaa20c8272a7aab2fd59

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
