# https://github.com/moby/buildkit/blob/master/examples/kube-consistent-hash/buildkitd-rootless-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: buildkitd
spec:
  serviceName: buildkitd
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
        status: accepts-new-builds
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
# see buildkit/docs/rootless.md for caveats of rootless mode
    spec:
      containers:
      - name: buildkitd
        image: moby/buildkit:v0.8.3-rootless@sha256:dad8bedca9dc0475bca3dbbc6e7e6c6bbf0cf8fa37ffe9b55629ac742f038288
        args:
        - --addr
        - unix:///run/user/1000/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:8547
        - --oci-worker-no-process-sandbox
        ports:
        - containerPort: 8547
        readinessProbe:
          exec:
            command:
            - buildctl
            - debug
            - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - buildctl
            - debug
            - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: etc-buildkit
          mountPath: /home/user/.config/buildkit
      volumes:
      - name: etc-buildkit
        configMap:
          name: etc-buildkit
