apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/Yolean/kubernetes-assert/runtime-nodejs/kustomize?ref=cae925e86004a4ecfe852aec3b54ee8f01c2063a
namePrefix: ystack-
commonLabels:
  app: ystack
images:
- name: yolean/assert-runtime-nodejs
  newName: builds-registry.ystack.svc.cluster.local/yolean/ystack-specs
