apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  template:
    spec:
      containers:
      - name: docker-v2
        env:
        - name: REGISTRY_STORAGE
          value: gcs
        - name: REGISTRY_STORAGE_GCS_BUCKET
          valueFrom:
            secretKeyRef:
              name: registry-persistence
              key: gcsBucketName
