
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ystack # install's app_url depends on namespace

resources:
- gitea-install.yaml

generatorOptions:
 disableNameSuffixHash: true # The git-automation secret is meant to be used by other services, and besides: kustomize wouldn't update the secretKeyRef

secretGenerator:
- name: git-automation
  literals:
  - endpoint=http://git.ystack.svc.cluster.local/api
  - username=ystack-admin
  - password=ystack-admin-temp
