apiVersion: batch/v1
kind: Job
metadata:
  name: bucket-create-ystack-builds
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:RELEASE.2020-07-11T05-18-52Z@sha256:fd5c0b878f2f1d2b531d966c599a78055aaf334c0a47ac66e20f40fae0e54d9a
        env:
        - name: MINIO_HOST
          value: http://blobs-minio
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        - name: MINIO_REGION
          value: us-east-1
        - name: BUCKET_NAME
          # TODO all from secret, except host maybe
          value: ystack-builds-registry
        command:
        - sh
        - -ce
        - |
          sleep 10
          mc config host add ystack $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          mc stat ystack/$BUCKET_NAME || {
            mc mb --region="$MINIO_REGION" ystack/$BUCKET_NAME
          }
      restartPolicy: Never
  backoffLimit: 10
